twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        project_directory: '%project_directory%'
        twig_base: '%twig_base%'

when@dev:
    parameters:

when@prod:
    parameters:

when@test:
    twig:
        strict_variables: true
